### ISSUE TITLE
Oracle binheap and current binheap are different.

### ISSUE THREAD

**Issue by una-dinosauria** [technicolor-research/pq-fast-scan#2]
I am trying `./pqfastscan` on my own data but I seem to be doing something wrong.

After compiling my codes, queries, tables and ids I get the following error:

```
$ ./pqfastscan partition0.dat queries.bvecs tables.fvecs ids0.txt 
Oracle binheap and current binheap are different.
Oracle binheap : [100] 
681568:-219584 | 833813:-206239 | 387028:-204958 | 892983:-202356 | 65908:-200099 | 
[... many more]
Current binheap : [100] 
2565:-185349 | 2646:-165327 | 2661:-157810 | 2559:-156902 | 2039:-152523 | 4078:-148696 |
[... many more]
```

I must say that in my case I'm using 7 tables of dot products and the last table contains the norm of the database element. I.e., to compute the distance between a  `d`-dimensional query `q` and an encoded database element `b = [b1, b2, ..., b7]`, the correct way of calculating a ranking is

`( sum_i^7 -2*q*C1[b1] ) + C8[b8]`

Where `C8` is a lookup table that quantizes the norms of the database (and `b8` is the corresponding code).

I figured that since this is still a lookup-based sum, the code would work out of the box, but this suggests that I have to modify something else. Do you have any pointers on what I could be doing wrong?

Cheers,

**Comment by fandre90** [comment]
Hi,

I don't have much time to look into this issue right now, and I think it would require quite a bit of work. What I can do however is tell you what the code precisely does, and hopefully this will help you figuring out what does not work.

PQ Fast Scan checks itself agains the seminal PQ Scan algorithm (which we call "oracle").
PQ Scan computes distances as follows:

![](http://quicklatex.com/cache3/b7/ql_c3c8f51fe5980b17376a2ee03b8b47b7_l3.png)

where ![](http://quicklatex.com/cache3/27/ql_95973dfdeaf50d0776b2b22d2e637027_l3.png) are the normal PQ lookup tables.

PQ Fast Scan uses "small tables" ![](http://quicklatex.com/cache3/32/ql_fb5d828dadce117be7c7414b3e3e6f32_l3.png) to compute lower bounds on distances and discard nearest neighbor candidates. In other words, for PQ Fast Scan to work, the following property must be true : 

![](http://quicklatex.com/cache3/c8/ql_7e6aa13bb17485ab9c3f5f83f05097c8_l3.png)

I am not sure this property holds in your example, ie: 

![](http://quicklatex.com/cache3/44/ql_838d1765ab405029594e9a58a5521b44_l3.png)

as there are mixed additions and substractions. I am almost sure there is a way to tweak PQ Fast Scan so that it works in this case (maybe store upper bounds in ![](http://quicklatex.com/cache3/df/ql_56126c61cce8c7c332297298c6202bdf_l3.png) and lower bounds in ![](http://quicklatex.com/cache3/33/ql_1945d9b84e530ffff42d406741590f33_l3.png)).

What is sure is that there is an issue with the way distances are computed. In `681568:-219584`, `681568` is the vector ID and `-219584` is the distance to the query vector, which should not be less than 0.

**Comment by una-dinosauria** [comment]
Thanks! This makes a lot of sense. I assumed there would be some sort of mis-correspondence with ground truth. I do realize that this is outside the scope of your paper so I'll close the issue.

Just as a coda, I'll give some context:
I am adapting the code to work for a variety of methods where the codebooks are full-dimensional, .e.g ![gif 3](https://cloud.githubusercontent.com/assets/3733964/12567363/7c502be4-c373-11e5-9d36-f00c5e2cbf86.gif) (as opposed to PQ, where ![gif 4](https://cloud.githubusercontent.com/assets/3733964/12569180/52e40010-c381-11e5-8b2c-a27204ea8fc5.gif)).

Vectors in the database are still approximated as a sum of entries in the codebooks: 
![gif 2](https://cloud.githubusercontent.com/assets/3733964/12567337/551724ec-c373-11e5-9d9a-dcd8bfdbb56d.gif)
but notice that this complicates the distance computation a little bit, as 

![gif 5](https://cloud.githubusercontent.com/assets/3733964/12569260/fbbac872-c381-11e5-86a4-7791998773ce.gif)

so a common technique is to quantize the inter-codebook products (the last term) in another table (e.g. on [this cvpr 2014 paper](http://www.cv-foundation.org/openaccess/content_cvpr_2014/papers/Babenko_Additive_Quantization_for_2014_CVPR_paper.pdf)) -- it is also common to sum the 2nd and 3rd terms to use a single table, and to skip the addition of the first term, as it is a constant and it does not affect the final ranking; thus, the result of the addition can be negative, even if the distance is not.

So, yeah, it seems like it requires a bit more work, but I believe with a few modifications the idea of pqscan should still apply. I'm curious to see if, with better quantization, the pruning factor can be increased and thus your code will give 5-6x speedups on datasets in the 2-3M range -- or better speedups in 6-25M datasets.

Thanks for your time!
